### ISSUE TITLE
Publish via Thunderbird add-on repository

### ISSUE THREAD

**Issue by renne** [verisign/smaug-tbird-plugin#2]
German e-mail providers like [Core-networks](https://www.core-networks.de/faq/smimea.html), [mail.de](https://mail.de/hilfe/nachrichten-s-mime-key-veroeffentlichen) and [posteo](https://posteo.de/en/blog/new-posteo-public-key-directory) support SMIMEA resource records.

Please publish this plug-in in the official Thunderbird add-on repository.

**Comment by beerisgood** [comment]
*push*

**Comment by beerisgood** [comment]
*Push*

**Comment by sean** [comment]
The repository will be archived. Feel free to fork and use the code under the terms of its license.
